# Generated by Django 4.0a1 on 2021-10-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='gallery/')),
                ('image_name', models.CharField(max_length=30)),
                ('image_description', models.TextField()),
            ],
        ),
    ]
