# Generated by Django 4.0a1 on 2021-10-11 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_category_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
